name: CI/CD Pipeline 23

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the appropriate version for your project

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build  # Replace with your build command if different

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Replace with your test command

    - name: Code Coverage
      run: npm run coverage  # Replace with your code coverage command if applicable

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Ensure deployment happens only on the main branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging
      run: ./deploy.sh  # Replace with your deployment script or command
